### PR TITLE
Autoresponder Multi recipients feature

### LINKED ISSUE #2275: CC and BCC for auto-responder are not passed to cf pro properly
I need to look at git history for the cc/bcc feature and look at what went wrong here. This is why I want to focus testing on interoperability between CF and CF Pro.

### PR DESCRIPTION
**Pull request by New0**
Merged feature/2278 into feature/2275  before this PR
This fixes #2275 and #2278
This allow the Auto responder processor to accept coma seperated lists of email addresses in recipient, Cc and Bcc fields

### CODE REVIEW

File: classes/core.php [hunk 1]
```diff
@@ -1029,10 +1029,22 @@ public static function send_auto_response( $config, $form ) {
 		// setup mailer
 		$subject = $config[ 'subject' ];
 
+		if( Caldera_Forms_Email_Prepare::is_list( $config[ 'recipient_email' ] ) ){
+            $recipients = Caldera_Forms_Email_Prepare::prepare_email_array( explode(',', $config[ 'recipient_email' ] ));
+            $send_local = \calderawp\calderaforms\pro\container::get_instance()->get_settings()->get_form( $form[ 'ID' ])->should_send_local();
+            if( $send_local ) {
+                foreach( $recipients as $recipient) {
+                    $f_recipients[] = $recipient[ 'name' ] . ' <' . $recipient[ 'email' ] . '>';
```
Comment (Shelob9) [inline classes/core.php]: @New0 Please use the full words for `$f` probably `$full`

**Comment by Shelob9** [comment]
Looks good. @New0 Please describe how to test - @robwilde Please walk through those tests.

**Comment by New0** [comment]
Tests to be run with Pro activated and deactivated

- Add an auto responder processor to the form

First test with comma seperated list of email addresses in the recipients, CC and Bcc fields
Second test with one email address in the recipients, CC and Bcc fields
