### PR TITLE
Fix json_decode expects parameter 1 to be a string admin.php L963

### LINKED ISSUE #1996: json_decode produces warning with code using get_entries for certain types of entries
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
* WordPress Version: 4.8.2
* PHP Version: 7.0.24
* MySQL Version: 5.6.36
* Caldera Forms Version: 1.5.6.1
* WP_DEBUG: false

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
Using [this code](https://calderaforms.com/doc/get-entries-from-a-form/) in Docs produces a PHP warning:
`json_decode() expects parameter 1 to be string` on this line: 
https://github.com/CalderaWP/Caldera-Forms/blob/master/classes/admin.php#L966

It doesn't happen for all forms/entries. It works fine for some and not for others. The only difference I can tell is that the forms it's not working for have entries that are showing some custom fields in the entries table whereas others are just showing the default fields in the entries table.

## Potential Fix
Switching the line above from `json_decode` to `maybe_unserialize` seems to resolve the issue but would need further testing.

### PR DESCRIPTION
**Pull request by New0**
Closes #1996 Caldera_Forms_Admin::get_entries returned a notice for json_decode that actually caused issues.

### CODE REVIEW

File: classes/admin.php [hunk 1]
```diff
@@ -960,7 +960,12 @@ public static function get_entries( $form_or_id, $page = 1, $perpage = 20, $stat
 							$field = Caldera_Forms_Field_Util::get_field(  $row->slug, $form, true );
 
 							// maybe json?
-							$is_json = json_decode( $row->value, ARRAY_A );
+                            if ( is_string($row->value) ) {
```
Comment (Shelob9) [inline classes/admin.php]: @New0  can you fix these indents please ? 

related #2206

**Comment by Shelob9** [comment]
@New0 This looks good.

Please do the following QA:

1) Check this PR out on the test site and run all tests. I can't see how this would cause any of them to fail since they are all front-end, but sometimes code in `Caldera_Forms_Admin` is used for something front-end. Those "sometimes" get us.
2) Create a form with 3 checkbox fields. Submit with field 1 having checked one option and field 2 having checked multiple options and field 3 having no options correct. Observe how this data is represented in the entry viewer, email, auto-responder and database.
