### PR TITLE
Ensure `\Caldera_Forms_Forms::get_forms:()` returns forms added on a filter.

### LINKED ISSUE #3341: External forms are not available in the widget
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 5.2.3PHP Version: 7.2.22MySQL Version: 5.6.45Caldera Forms Version: 1.8.7WP_DEBUG: 1

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
When external forms are included using the 'caldera_forms_get_forms' they are not available in the widget.

## Cause
This happens because the variable $forms in which they are stored gets overwritten a few lines later.

https://github.com/CalderaWP/Caldera-Forms/blob/ff614a4bd16381f92d6314a0d2f907f4951938d2/classes/forms.php#L186-L199

## What PHP Errors Have You Logged While Reproducing This Bug?
none

## What JavaScript Errors Have You Seen While Reproducing This Bug?
none

### LINKED ISSUE #3345: Programatically created Form does not play well with DB created Form
Caldera relies on the `caldera_forms_get_forms` filter to provide an "existence" to the Forms that were created programmatically and does not exist in the database.

That filter is applied in `\Caldera_Forms_Forms::get_forms`: https://github.com/CalderaWP/Caldera-Forms/blob/master/classes/forms.php#L178-L199

It applies the filter at line 186, but overrides it again to the original value on line 198.

Despite that, methods such as `\Caldera_Forms::render_form` might continue working, because of a `!empty($forms)` assertion. Check line 4278 of `core.php`: https://github.com/CalderaWP/Caldera-Forms/blob/master/classes/core.php#L4278

That probably means that two bugs co-exist generating an erratic behavior. If `$forms` return empty, it will not try to check for the existence of the Form, thus will continue the processing and will actually output the form. If `$forms` contain anything (such as a form saved on the database), it will assert if the form ID we are trying to render exists. That will fail because the filter was overridden, so `render_form` will just return null.

Possible solution:

Before:
```
if( $with_details ){
	$forms = self::add_details( static::$index );
}else{
	$forms = static::$index;
}
```

After:
```
if( $with_details ){
	$forms = self::add_details( static::$index );
}
```

### PR DESCRIPTION
**Pull request by Shelob9**
This PR fixes #3345 

It also fixes #3341

When I test with this branch, I see the form added using a filter int he Gutenberg block, form entry viewer and widget.

I think I got both of the bugs that @Luc45 said ` co-exist generating an erratic behavior` [here](https://github.com/CalderaWP/Caldera-Forms/issues/3345#issue-492514529).

I prevented  the overwrite of `$forms` here:
https://github.com/CalderaWP/Caldera-Forms/pull/3354/files#diff-634fa6588d7d78d435ea1ea46e18563cR195-R199

I also prevented forms added on a filter from being removed here:
https://github.com/CalderaWP/Caldera-Forms/pull/3354/files#diff-634fa6588d7d78d435ea1ea46e18563cL417

Note, I am intentionally bypassing reading from caching of that variable. I'm not worried about the performance, I am worried about bugs caused by WHEN the filter runs.

Also, I expanded the test that SHOULD have been covering this filter, but didn't tests these situations. I left my assumptions as inline comments:
https://github.com/CalderaWP/Caldera-Forms/pull/3354/files#diff-8c0dd687d0ffb15b67072a3555cb2700L73

### CODE REVIEW

File: classes/forms.php [hunk 1]
```diff
@@ -411,15 +411,11 @@ protected function force_string( $val ){
...
+			return [];
         }
 
-        if( ! empty( $valid_forms = get_transient( self::$registry_cache_key ) ) ) {
-            return $valid_forms;
-        }else{
-            $valid_forms = [];
-        }
-		
+		$valid_forms = [];
```
Comment (kjohnson) [inline classes/forms.php]: In the PR you callout intentionally bypassing the cache, but once merged that decision will be buried, so it may be helpful to add a comment to explain the intent of bypassing the cache.

Comment (Shelob9) [reply classes/forms.php]: Good point. Added in https://github.com/CalderaWP/Caldera-Forms/commit/1a6a1e0c69fa2152df0e64e5ac8dc2c8e937ba88

**Comment by Shelob9** [comment]
@New0 Your change in 700abcc4ac6a436de34a5f40aaa32f356871df56 makes sense to me. Either I counted wrong or we added another form there since I wrote this. That's why this type of test is NOT ideal. But, it's fine for now.
